/**
 * Opt-in check against a genuine Instagram export.
 *
 * Real export files are gitignored, so this suite skips itself when none are present.
 * To run it, drop your own `followers*.html` / `following*.html` next to package.json.
 *
 * The assertions deliberately derive their expectations from the file itself rather
 * than hardcoding names or counts, so nothing personal ends up in the repository.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildCurrentState, nonFollowers } from '../src/analysis/currentState';
import { diffSnapshots } from '../src/analysis/diff';
import { parseRawFiles, type RawFile } from '../src/parser';
import type { Snapshot } from '../src/model/types';

const ROOT = join(import.meta.dirname, '..');

function findRealExports(): RawFile[] {
  let names: string[];
  try {
    names = readdirSync(ROOT);
  } catch {
    return [];
  }
  return names
    .filter((n) => /^(followers|following).*\.html$/i.test(n))
    .map((name) => {
      const text = readFileSync(join(ROOT, name), 'utf8');
      return { path: name, text, bytes: Buffer.byteLength(text) };
    });
}

const realFiles = findRealExports();
const HANDLE_RE = /^[a-z0-9._]{1,30}$/;

describe.skipIf(realFiles.length === 0)('a real Instagram export', () => {
  const snapshot = parseRawFiles(realFiles);

  it('places every file into a known list', () => {
    expect(snapshot.sourceFiles.every((f) => f.kind !== 'unmatched')).toBe(true);
    expect(snapshot.kindsPresent.length).toBeGreaterThan(0);
  });

  it('reads exactly as many accounts as the file contains entry blocks', () => {
    for (const file of snapshot.sourceFiles) {
      const source = realFiles.find((f) => f.path === file.path)!;
      // Counted inside <main> only: the stylesheet also defines a .uiBoxWhite rule.
      const main = source.text.slice(source.text.indexOf('<main'), source.text.indexOf('</main>'));
      const blocks = main.split('uiBoxWhite').length - 1;
      expect(blocks, `${file.path} should have entry blocks`).toBeGreaterThan(0);
      expect(file.entryCount, `${file.path} entry count`).toBe(blocks);
    }
  });

  it('produces clean handles, never URLs or deep-link fragments', () => {
    for (const observation of snapshot.observations) {
      expect(observation.handle, observation.handle).toMatch(HANDLE_RE);
      expect(observation.handle.startsWith('_u')).toBe(false);
    }
  });

  it('recovers a follow date for every account', () => {
    const missing = snapshot.observations.filter((o) => o.followedAt === undefined);
    expect(missing).toHaveLength(0);
  });

  it('never mistakes a username for part of a date', () => {
    for (const observation of snapshot.observations) {
      expect(observation.followedAtRaw?.toLowerCase()).not.toContain(observation.handle);
    }
  });

  it('reads the export date and owner out of the document header', () => {
    expect(snapshot.exportedAtSource).toBe('document_header');
    expect(Number.isNaN(Date.parse(snapshot.exportedAt))).toBe(false);
    expect(snapshot.generatedBy).toMatch(HANDLE_RE);
    expect(snapshot.coverage).toBeDefined();
  });

  it('parses without any structural problem', () => {
    // A truncation notice describes the export's own date range, not a parsing failure,
    // so it is allowed here. Anything else means the reader struggled with the file.
    const structural = snapshot.warnings.filter((w) => w.code !== 'possibly_truncated');
    expect(structural).toEqual([]);
  });
});

describe.skipIf(realFiles.length === 0)('keeping real data out of the repository', () => {
  /**
   * This repository is public and real exports are routinely dropped into it while
   * developing. Copying a genuine username into a fixture is an easy mistake to make
   * and an impossible one to spot by eye, so it is checked instead.
   */
  it('never mentions a real username in a tracked file', () => {
    const realHandles = new Set<string>();
    for (const file of realFiles) {
      for (const [, handle] of file.text.matchAll(/instagram\.com\/(?:_u\/)?([A-Za-z0-9._]{1,30})"/g)) {
        // Short handles produce false matches inside lockfile hashes.
        if (handle.length >= 6) realHandles.add(handle.toLowerCase());
      }
    }
    for (const [, owner] of realFiles[0].text.matchAll(/generated by\s+([A-Za-z0-9._]{1,30})\s+on/gi)) {
      realHandles.add(owner.toLowerCase());
    }
    expect(realHandles.size).toBeGreaterThan(0);

    const tracked = execFileSync('git', ['ls-files', 'src', 'tests', 'README.md'], {
      cwd: ROOT,
      encoding: 'utf8',
    })
      .split('\n')
      .filter(Boolean);

    const leaks: string[] = [];
    for (const path of tracked) {
      const contents = readFileSync(join(ROOT, path), 'utf8').toLowerCase();
      for (const handle of realHandles) {
        if (contents.includes(handle)) leaks.push(`${path} contains "${handle}"`);
      }
    }

    expect(leaks).toEqual([]);
  });
});

describe.skipIf(realFiles.length < 2)('analysing a real export', () => {
  const parsed = parseRawFiles(realFiles);
  const saved: Snapshot = {
    ...parsed,
    id: 'real',
    label: 'Real export',
    importedAt: parsed.exportedAt,
  };

  it('keeps the relationship counts internally consistent', () => {
    const { counts, rows } = buildCurrentState(saved);
    expect(counts.mutuals + counts.notFollowingBack).toBe(counts.following);
    expect(counts.mutuals + counts.youDoNotFollowBack).toBe(counts.followers);
    expect(rows.length).toBe(counts.mutuals + counts.notFollowingBack + counts.youDoNotFollowBack);
  });

  it('finds accounts that do not follow back', () => {
    const state = buildCurrentState(saved);
    const missing = nonFollowers(state);
    expect(missing.length).toBe(state.counts.notFollowingBack);
    expect(missing.every((r) => r.isFollowing && !r.isFollower)).toBe(true);
  });

  it('reports no change at all when compared against itself', () => {
    const diff = diffSnapshots(saved, { ...saved, id: 'copy', label: 'Copy' });
    for (const kind of diff.kinds) {
      expect(kind.comparable, kind.kind).toBe(true);
      expect(kind.appeared, kind.kind).toEqual([]);
      expect(kind.disappeared, kind.kind).toEqual([]);
    }
    expect(diff.renames).toEqual([]);
  });

  it('refuses to declare hundreds of departures when a real file goes missing', () => {
    const withoutFollowing: Snapshot = {
      ...saved,
      id: 'partial',
      label: 'Partial',
      kindsPresent: saved.kindsPresent.filter((k) => k !== 'following'),
      observations: saved.observations.filter((o) => o.kind !== 'following'),
    };

    const following = diffSnapshots(saved, withoutFollowing).kinds.find(
      (k) => k.kind === 'following',
    )!;
    expect(following.comparable).toBe(false);
    expect(following.disappeared).toEqual([]);
  });
});
