/**
 * Recovering when an export was produced.
 *
 * Instagram HTML files carry this in their own header, which removes all guesswork:
 *
 *   <aside role="contentinfo">Generated by <user> on <time datetime="2026-08-19T16:02Z">...</time>
 *     <div>Contains data you requested from <time datetime="..."> to <time datetime="..."></div>
 *   </aside>
 *
 * Note the `datetime` attribute and the human text next to it can disagree by a few
 * hours in real exports. The attribute is used because it is unambiguous to parse, and
 * hours of skew do not affect snapshot ordering or labelling.
 */

import type { CoverageWindow } from '../model/types';

export interface DocumentHeader {
  generatedAt?: string;
  generatedBy?: string;
  coverage?: CoverageWindow;
}

export function readDocumentHeader(doc: Document): DocumentHeader {
  const aside = doc.querySelector('aside[role="contentinfo"]') ?? doc.querySelector('aside');
  if (!aside) return {};

  const times = Array.from(aside.querySelectorAll('time[datetime]'))
    .map((el) => el.getAttribute('datetime'))
    .filter((value): value is string => Boolean(value))
    .map((value) => (Number.isNaN(Date.parse(value)) ? null : new Date(value).toISOString()))
    .filter((value): value is string => value !== null);

  const header: DocumentHeader = {};
  if (times[0]) header.generatedAt = times[0];
  if (times[1] && times[2]) header.coverage = { from: times[1], to: times[2] };

  const byMatch = /generated by\s+([A-Za-z0-9._]{1,30})\s+on/i.exec(aside.textContent ?? '');
  if (byMatch) header.generatedBy = byMatch[1].toLowerCase();

  return header;
}

/** Instagram names archives like `instagram-someone-2026-08-19-A1b2C3.zip`. */
export function dateFromArchiveName(name: string): string | undefined {
  const match = /(\d{4})-(\d{2})-(\d{2})/.exec(name);
  if (!match) return undefined;
  const epoch = Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
  return Number.isNaN(epoch) ? undefined : new Date(epoch).toISOString();
}
