/**
 * Synthetic Instagram exports.
 *
 * The markup here mirrors a real "Download your information" HTML export closely,
 * including the two details that differ between its files: `following.html` links
 * through `/_u/` and prints the full URL as the link text, while `followers_1.html`
 * links directly and prints the bare handle.
 */

export interface FixtureEntry {
  handle: string;
  /** Printed exactly as the export prints it, e.g. "Aug 01, 2026 9:09 am". */
  timestamp?: string;
  /** Overrides the href, for testing non-profile links. */
  href?: string;
}

export interface FixtureOptions {
  heading?: string;
  entries?: FixtureEntry[];
  /** `following` uses the /_u/ deep link and URL link text. */
  linkStyle?: 'followers' | 'following';
  generatedBy?: string;
  generatedAt?: string;
  coverage?: { from: string; to: string };
  omitAside?: boolean;
  omitHeading?: boolean;
}

function entryBlock(entry: FixtureEntry, linkStyle: 'followers' | 'following'): string {
  const href =
    entry.href ??
    (linkStyle === 'following'
      ? `https://www.instagram.com/_u/${entry.handle}`
      : `https://www.instagram.com/${entry.handle}`);
  const text = linkStyle === 'following' ? href : entry.handle;
  const time = entry.timestamp ? `<div>${entry.timestamp}</div>` : '';
  return (
    '<div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder"><div class="_a6-p"><div>' +
    `<div><a target="_blank" href="${href}">${text}</a></div>${time}` +
    '</div></div></div>'
  );
}

export function buildExportHtml(options: FixtureOptions = {}): string {
  const {
    heading = 'Followers',
    entries = [],
    linkStyle = 'followers',
    generatedBy = 'testuser',
    generatedAt = '2026-08-19T16:02Z',
    coverage = { from: '2025-07-23T21:00Z', to: '2026-08-08T21:00Z' },
    omitAside = false,
    omitHeading = false,
  } = options;

  const aside = omitAside
    ? ''
    : `<aside role="contentinfo" class="_aoaa">Generated by ${generatedBy} on ` +
      `<time datetime="${generatedAt}">generated</time>` +
      `<div>Contains data you requested from <time datetime="${coverage.from}">from</time>` +
      ` to <time datetime="${coverage.to}">to</time></div></aside>`;

  const h1 = omitHeading ? '' : `<h1>${heading}</h1>`;
  const blocks = entries.map((e) => entryBlock(e, linkStyle)).join('');

  return (
    '<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />' +
    `<base href="../../" /><title>${omitHeading ? '' : heading}</title></head>` +
    `<body class="_5vb_"><div class="_li"><div class="_a705"><header class="_as-_ _a70a">` +
    `<div class="_a70d">${h1}${aside}</div></header>` +
    `<main class="_a706" role="main">${blocks}</main></div></div></body></html>`
  );
}

/** Generates `count` plausible handles so bulk behaviour can be exercised. */
export function handles(prefix: string, count: number): FixtureEntry[] {
  return Array.from({ length: count }, (_, i) => ({
    handle: `${prefix}_${i}`,
    timestamp: `Jul ${String((i % 28) + 1).padStart(2, '0')}, 2026 9:0${i % 10} am`,
  }));
}
